---
- hosts: "{{ host_for_passwd }}"
  vars_files:
    - /iac/repo/scripts/credentials_pwreset.yml 
    - /iac/repo/scripts/hostname_pwreset.yml
    - /iac/repo/scripts/username_pwreset.yml

  vars:
    password: "{{ my_default_password }}"
    username: "{{ user_name }}"


  tasks:
  - name: Change user password
    user: name={{ user_name }} update_password=always password={{ password }}
